### ISSUE TITLE
compiled error

### ISSUE THREAD

**Issue by bj-edward** [LENSHOOD/xv6-rust#1]
For rustc 1.85.0-nightly (acabb5248 2024-12-04):

error[E0599]: no method named `expose_addr` found for raw pointer `*const u8` in the current scope
   --> src/proc.rs:522:65
    |
522 |     let trampoline_addr = (unsafe { &trampoline } as *const u8).expose_addr();
    |                                                                 ^^^^^^^^^^^ method not found in `*const u8`

error[E0599]: no method named `expose_addr` found for raw pointer `*const Trapframe` in the current scope
   --> src/proc.rs:537:79
    |
537 |     let trapframe_addr = (*p.trapframe.as_ref().unwrap() as *const Trapframe).expose_addr();
    |                                                                               ^^^^^^^^^^^ method not found in `*const Trapframe`

error[E0599]: no method named `expose_addr` found for raw pointer `*mut u8` in the current scope
   --> src/proc.rs:563:17
    |
563 |             dst.expose_addr(),
    |                 ^^^^^^^^^^^ method not found in `*mut u8`

error[E0599]: no method named `expose_addr` found for raw pointer `*const u8` in the current scope
   --> src/proc.rs:582:17
    |
582 |             src.expose_addr(),
    |                 ^^^^^^^^^^^ method not found in `*const u8`

error[E0599]: no method named `expose_addr` found for raw pointer `*const u8` in the current scope
  --> src/trap.rs:34:50
   |
34 |     w_stvec((unsafe { &kernelvec } as *const u8).expose_addr());
   |                                                  ^^^^^^^^^^^ method not found in `*const u8`

error[E0599]: no method named `expose_addr` found for raw pointer `*const u8` in the current scope
  --> src/trap.rs:48:50
   |
48 |     w_stvec((unsafe { &kernelvec } as *const u8).expose_addr());
   |                                                  ^^^^^^^^^^^ method not found in `*const u8`

error[E0599]: no method named `expose_addr` found for raw pointer `*const u8` in the current scope
   --> src/trap.rs:112:59
    |
112 |     let uservec_addr = (unsafe { &uservec } as *const u8).expose_addr();
    |                                                           ^^^^^^^^^^^ method not found in `*const u8`

error[E0599]: no method named `expose_addr` found for raw pointer `*const u8` in the current scope
   --> src/trap.rs:113:65
    |
113 |     let trampoline_addr = (unsafe { &trampoline } as *const u8).expose_addr();
    |                                                                 ^^^^^^^^^^^ method not found in `*const u8`

error[E0599]: no method named `expose_addr` found for raw pointer `*const PageTable` in the current scope
   --> src/trap.rs:139:70
    |
139 |     let satp = MAKE_SATP!((p.pagetable.unwrap() as *const PageTable).expose_addr());
    |                                                                      ^^^^^^^^^^^ method not found in `*const PageTable`

error[E0599]: no method named `expose_addr` found for raw pointer `*const u8` in the current scope
   --> src/trap.rs:144:59
    |
144 |     let userret_addr = (unsafe { &userret } as *const u8).expose_addr();
    |                                                           ^^^^^^^^^^^ method not found in `*const u8`

error[E0599]: no method named `expose_addr` found for raw pointer `*mut virtio::VirtqDesc` in the current scope
   --> src/virtio/virtio_disk.rs:169:52
    |
169 |     Write_R!(VIRTIO_MMIO_QUEUE_DESC_LOW, DISK.desc.expose_addr() as u32);
    |                                                    ^^^^^^^^^^^ method not found in `*mut VirtqDesc`

error[E0599]: no method named `expose_addr` found for raw pointer `*mut virtio::VirtqDesc` in the current scope
   --> src/virtio/virtio_disk.rs:172:20
    |
172 |         (DISK.desc.expose_addr() >> 32) as u32
    |                    ^^^^^^^^^^^ method not found in `*mut VirtqDesc`

error[E0599]: no method named `expose_addr` found for raw pointer `*mut virtio::VirtqAvail` in the current scope
   --> src/virtio/virtio_disk.rs:174:54
    |
174 |     Write_R!(VIRTIO_MMIO_DRIVER_DESC_LOW, DISK.avail.expose_addr() as u32);
    |                                                      ^^^^^^^^^^^ method not found in `*mut VirtqAvail`

error[E0599]: no method named `expose_addr` found for raw pointer `*mut virtio::VirtqAvail` in the current scope
   --> src/virtio/virtio_disk.rs:177:21
    |
177 |         (DISK.avail.expose_addr() >> 32) as u32
    |                     ^^^^^^^^^^^ method not found in `*mut VirtqAvail`

error[E0599]: no method named `expose_addr` found for raw pointer `*mut virtio::VirtqUsed` in the current scope
   --> src/virtio/virtio_disk.rs:179:53
    |
179 |     Write_R!(VIRTIO_MMIO_DEVICE_DESC_LOW, DISK.used.expose_addr() as u32);
    |                                                     ^^^^^^^^^^^ method not found in `*mut VirtqUsed`

error[E0599]: no method named `expose_addr` found for raw pointer `*mut virtio::VirtqUsed` in the current scope
   --> src/virtio/virtio_disk.rs:182:20
    |
182 |         (DISK.used.expose_addr() >> 32) as u32
    |                    ^^^^^^^^^^^ method not found in `*mut VirtqUsed`

error[E0599]: no method named `expose_addr` found for raw pointer `*mut virtio::VirtioBlkReq` in the current scope
   --> src/virtio/virtio_disk.rs:232:52
    |
232 |     virt_desc_0.addr = (buf0 as *mut VirtioBlkReq).expose_addr() as u64;
    |                                                    ^^^^^^^^^^^ method not found in `*mut VirtioBlkReq`

error[E0599]: no method named `expose_addr` found for raw pointer `*const u8` in the current scope
   --> src/virtio/virtio_disk.rs:238:47
    |
238 |     virt_desc_1.addr = (&b.data as *const u8).expose_addr() as u64;
    |                                               ^^^^^^^^^^^ method not found in `*const u8`

error[E0599]: no method named `expose_addr` found for raw pointer `*const u8` in the current scope
   --> src/virtio/virtio_disk.rs:251:65
    |
251 |     virt_desc_2.addr = (&DISK.info[idx[0]].status as *const u8).expose_addr() as u64;
    |                                                                 ^^^^^^^^^^^ method not found in `*const u8`

error[E0599]: no method named `expose_addr` found for raw pointer `*const u8` in the current scope
  --> src/vm.rs:46:55
   |
46 |     let etext_addr = (unsafe { &etext } as *const u8).expose_addr();
   |                                                       ^^^^^^^^^^^ method not found in `*const u8`

error[E0599]: no method named `expose_addr` found for raw pointer `*const u8` in the current scope
  --> src/vm.rs:68:64
   |
68 |     let trapoline_addr = (unsafe { &trampoline } as *const u8).expose_addr();
   |                                                                ^^^^^^^^^^^ method not found in `*const u8`

error[E0599]: no method named `expose_addr` found for raw pointer `*mut PageTable` in the current scope
   --> src/vm.rs:208:53
    |
208 |                 *pte = Pte(PA2PTE!(next_level_pgtbl.expose_addr()) | PTE_V);
    |                                                     ^^^^^^^^^^^ method not found in `*mut PageTable`

error[E0599]: no method named `expose_addr` found for raw pointer `*const PageTable` in the current scope
   --> src/vm.rs:249:73
    |
249 |     let addr = unsafe { (KERNEL_PAGETABLE.unwrap() as *const PageTable).expose_addr() };
    |                                                                         ^^^^^^^^^^^ method not found in `*const PageTable`

error[E0599]: no method named `expose_addr` found for raw pointer `*mut u8` in the current scope
   --> src/vm.rs:283:13
    |
283 |         mem.expose_addr(),
    |             ^^^^^^^^^^^ method not found in `*mut u8`

error[E0599]: no method named `expose_addr` found for raw pointer `*mut u8` in the current scope
   --> src/vm.rs:336:17
    |
336 |             mem.expose_addr(),
    |                 ^^^^^^^^^^^ method not found in `*mut u8`

error[E0599]: no method named `expose_addr` found for raw pointer `*mut u8` in the current scope
   --> src/vm.rs:396:33
    |
396 |         if mappages(new, i, mem.expose_addr(), PGSIZE, flags) != 0 {
    |                                 ^^^^^^^^^^^ method not found in `*mut u8`

error[E0599]: no method named `unwrap` found for struct `PanicMessage` in the current scope
  --> src/main.rs:61:28
   |
61 |             info.message().unwrap()
   |                            ^^^^^^ method not found in `PanicMessage<'_>`

**Comment by LENSHOOD** [comment]
I've tried `1.85.0-nightly` and got a same failure too😅

It seems that the function `expose_addr()` has been removed in the newer version, simply replace the `expose_addr()` to `addr()` solves the compilation error.

However, there maybe additional changes in the latest build, as the `balloc()` function is also failing to retrieve any available blocks. I will take another look at this matter shortly.

**Comment by LENSHOOD** [comment]
Hi @bj-edward, please note that I've fixed the `balloc()` issue, the root cause was I forgot `trasmute` back the indirect block when writing it back to the fs image, which resulted in missing block information. 

Even though I still haven't figured out why this issue didn't happen before, anyway the code can be run correctly based on the `1.85.0-nightly` now, please give it a shot once again, and if there are any further issues, feel free to contact me!
